let test = [{ pseudo: 'John McGrath john', mail: '' },
  { pseudo: 'John Papa johnpapa', mail: '' },
  { pseudo: 'John Sundell JohnSundell', mail: '' },
  { pseudo: 'John Myles White johnmyleswhite',
    mail: 'jmw@johnmyleswhite.com' },
  { pseudo: 'John D. Pope johndpope', mail: '' },
  { pseudo: 'John Lindquist johnlindquist', mail: '' },
  { pseudo: 'JohnGrib johngrib', mail: 'johngrib82@gmail.com' },
  { pseudo: 'John Otander johno', mail: 'johnotander@gmail.com' },
  { pseudo: 'John Lui johnlui', mail: '' },
  { pseudo: 'Evgeny Shishkin johnkil',
    mail: 'johnkil78@gmail.com' },
  { pseudo: 'John A. De Goes jdegoes', mail: 'john@degoes.net' },
  { pseudo: 'john-smilga', mail: '' },
  { pseudo: 'John Holdsworth johnno1962', mail: '' },
  { pseudo: 'John Resig jeresig', mail: 'jeresig@gmail.com' },
  { pseudo: 'John Polacek johnpolacek', mail: '' },
  { pseudo: 'John Fish johnafish', mail: '' },
  { pseudo: 'John Barnette jbarnette',
    mail: 'john@jbarnette.com' },
  { pseudo: 'John Britton johndbritton',
    mail: 'public@johndbritton.com' },
  { pseudo: 'John Hawthorn jhawthorn',
    mail: 'john@hawthorn.email' },
  { pseudo: 'John Stevenson jr0cket', mail: 'john@jr0cket.co.uk' },
  { pseudo: 'John O\'Nolan JohnONolan', mail: '' },
  { pseudo: 'johnil', mail: 'johnil@me.com' },
  { pseudo: 'john JohnTsaiAndroid', mail: '' },
  { pseudo: 'John Blackbourn johnbillion', mail: '' },
  { pseudo: 'P. Oscar Boykin johnynek', mail: '' },
  { pseudo: 'John Hammond JohnHammond', mail: '' },
  { pseudo: 'johnjohnsp1', mail: '' },
  { pseudo: 'Victor Berchet vicb', mail: 'victor@suumit.com' },
  { pseudo: 'William Lyon johnymontana', mail: '' },
  { pseudo: 'Tobias Preuss johnjohndoe', mail: '' },
  { pseudo: 'John Murowaniecki jmurowaniecki', mail: '' },
  { pseudo: 'John Drinkwater johndrinkwater',
    mail: 'john@johndrinkwater.name' },
  { pseudo: 'John McLear JohnMcLear', mail: 'john@mclear.co.uk' },
  { pseudo: 'Che-Wei Lin John-Lin', mail: 'linton.tw@gmail.com' },
  { pseudo: 'Roger D. Peng rdpeng', mail: '' },
  { pseudo: 'John Alexis Guerra Gómez john-guerra', mail: '' },
  { pseudo: 'John (JP) Coene JohnCoene',
    mail: 'jcoenep@gmail.com' },
  { pseudo: 'John Washam jwasham', mail: '' },
  { pseudo: 'John Leider johnleider', mail: 'john@vuetifyjs.com' },
  { pseudo: 'John Troon JohnTroony', mail: '' },
  { pseudo: 'John Bender johnbender', mail: '' },
  { pseudo: 'John Griffiths johnantoni', mail: 'john@red91.com' },
  { pseudo: 'John P. Bloch johnpbloch', mail: '' },
  { pseudo: 'John Thompson springframeworkguru', mail: '' },
  { pseudo: 'John Wong JohnWong', mail: '' },
  { pseudo: 'John Kenn johnnncodes', mail: '' },
  { pseudo: 'John Gracey jagracey', mail: '' },
  { pseudo: 'John Hobbs jmhobbs', mail: 'john@velvetcache.org' },
  { pseudo: 'John Wiegley jwiegley',
    mail: 'johnw@newartisans.com' },
  { pseudo: 'John JohnLangford', mail: 'jl@hunch.net' }];



console.log(test.length);

console.log(test[0]);


for(let k = 0; k<test.length; k++){
    console.log(test[k]);
  }